updaet an issue
Abbhiishek/codecommunitymusic-client pull request #24
Opened 2023-09-30 16:04 UTC by Debangan202Ok

@Abbhiishek check it.
https://github.com/Abbhiishek/codecommunitymusic-client/issues/14#issuecomment-1741765437

2023-09-30 18:08 UTC, Abbhiishek requested changes

2023-09-30 18:08 UTC, Abbhiishek commented on types/Contrbutor.ts
Well done..

can we make this scalable with a single contributors giving out more issuelinks and prlinks they have worked on. 

We would be building a contributors page i hope these data will help us built the page.

2023-09-30 18:21 UTC, Debangan202Ok commented on types/Contrbutor.ts
Sure! @Abbhiishek 

What should i do next?

2023-10-01 05:20 UTC, Abbhiishek commented on types/Contrbutor.ts
I pushed the new schema. Resolve the merge conflict and rest you are good to go

2023-10-01 08:38 UTC, Debangan202Ok reviewed
README.md modified

2023-10-01 14:05 UTC, Debangan202Ok commented
hello @Abbhiishek, 
please check my new commits

2023-10-01 15:01 UTC, Abbhiishek requested changes
Somone else is working with the documentation, If you want you can assit him in this issue #26 

I have defined the types , kindly use that.

2023-10-01 16:33 UTC, closed without merging